version: "3.3"

services:
  mysqldb:
    container_name: mysqldb
    image: mysql:latest
    restart: unless-stopped
    environment:
      MYSQL_ROOT_USERNAME: root
      MYSQL_ROOT_PASSWORD:
      MYSQL_DATABASE: tpachato
    volumes:
      - /home/mysql/data:/var/lib/mysql
    ports:
      - 3308:3306

  spring_app:
    image: 203jmt1067/tpachatproject
    container_name: tpachatproject

    restart: on-failure
    ports:
      - 8089:8089
    depends_on:
      - mysqldb